name: Doctests
on: [push, pull_request]
runs-on: ubuntu-latest
jobs:
  test:
    steps:
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 
      - name: Run doctest
        run: wasm-pack test --node
